---
title: "Resultados"
author: "Carlos Meijide Garcia"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library("tidyr")
library("ggplot2")

library("fda.usc")

#setwd("~/Modelo_Covid_descargado/Results/Extremadura/")

##############################
##### CAMBIAR DENDE AQUÍ #####
##############################

i=11 #indice da autonomia
i1_raw= read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_I1.txt")
i2_raw= read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_I2.txt")
i3_raw= read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_I3.txt")
r1_raw= read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_R1.txt")
r2_raw= read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_R2.txt")
mortos_raw=read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_XM.txt")
erro=read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_Error.txt")
reais_raw=read.table("../../src/Results/Espana/Extremadura/SimulaExtremadura_XM_Real.txt")


i1_raw$V1=i1_raw$V1+1
i2_raw$V1=i2_raw$V1+1
i3_raw$V1=i3_raw$V1+1
r1_raw$V1=r1_raw$V1+1
r2_raw$V1=r2_raw$V1+1
mortos_raw$V1=mortos_raw$V1+1

autonomias=read.csv("../../Data/Espana/Espana_Poblacion.csv",header=TRUE,sep=',')

reais=read.csv("../../Data/Espana/Espana_Fallecidos.csv",header=TRUE,sep=',')

####################
##### ATA AQUI #####
####################
poboacioni=as.numeric(autonomias[(autonomias[,1])==i,])[3]
reaisi=as.numeric(reais[(reais[,1])==i,])

nceros=0
j=0
while(reaisi[j+3]==0) {
  nceros=nceros+1
  j=j+1
  }



d=ncol(mortos_raw)
r= 18-nceros#numero de dias con antelacion cos que empeza o simulador

datas=seq( as.Date("2020-08-13")-r, by=1, len=d-1)
names(i1_raw)[-1]=format(datas,"%Y-%m-%d")
names(i2_raw)[-1]=format(datas,"%Y-%m-%d")
names(i3_raw)[-1]=format(datas,"%Y-%m-%d")
names(r1_raw)[-1]=format(datas,"%Y-%m-%d")
names(r2_raw)[-1]=format(datas,"%Y-%m-%d")
names(mortos_raw)[-1]=format(datas,"%Y-%m-%d")



morultimodia=as.double(erro[1])
distancias=(abs(mortos_raw[,ncol(mortos_raw)]-morultimodia))
```

```{r echo=FALSE}
hist(distancias,main="Last day error",xlab="Individuals")
plot(fdata(mortos_raw),main="All simulated fatality trajectories")

```


```{r message=FALSE, warning=FALSE, include=FALSE}
index=order(distancias)
ordenados=mortos_raw[index,]
ordenados$dis=distancias[index]
aceptados=ordenados[ordenados$dis<morultimodia*0.1,]
mortos=aceptados

aceptados[1,ncol(aceptados)]=-0.9 #para que soamente apareza unha liña grosa nas graficas que non son de M

moreais=c(-1,as.numeric(reais_raw[1,2:length(reais_raw)]),-1)
mortosconreais=rbind(aceptados,moreais)



mord=gather(mortosconreais,key="dia",value="cantos",-V1,-dis)

mord$dia=as.Date(mord$dia)

m=max(100*mord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p1=ggplot(mord[mord$dis!=-1,]) +
  geom_line(aes(dia, 100*cantos/poboacioni,group=
  V1,alpha=exp(-dis^2/(2*var(dis)))),colour='#00C08D',show.legend=FALSE) +
  geom_point(data=mord[mord$dis==-1,],aes(dia, 100*cantos/poboacioni),colour='black') +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +    scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("Fatality rate in ", autonomias$Comunidad[i]))
p1

 

i1=i1_raw[aceptados$V1,]
i1$dis=aceptados$dis


# library("fda.usc")
# trayectorias= i1[,-c(1,ncol(i1))]
# datosfda= fdata(trayectorias)
# plot(datosfda)
#  

i1ord=gather(i1,key="dia",value="cantos",-V1,-dis)
i1ord$dia=as.Date(i1ord$dia)
m=max(100*i1ord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p2=ggplot(i1ord) +
   geom_line(aes(dia, 100*cantos/poboacioni,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +  scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
  theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("% of I1 in ", autonomias$Comunidad[i]))
p2


i2=i2_raw[aceptados$V1,]
i2$dis=aceptados$dis

i2ord=gather(i2,key="dia",value="cantos",-V1,-dis)
i2ord$dia=as.Date(i1ord$dia)

m=max(100*i2ord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p3=ggplot(i2ord) +
    geom_line(aes(dia, 100*cantos/poboacioni,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("% of I2 in ", autonomias$Comunidad[i]))
p3


i3=i3_raw[aceptados$V1,]
i3$dis=aceptados$dis

i3ord=gather(i3,key="dia",value="cantos",-V1,-dis)
i3ord$dia=as.Date(i1ord$dia)

m=max(100*i3ord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p4=ggplot(i3ord) +
    geom_line(aes(dia, 100*cantos/poboacioni,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +  scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("% of I3 in ", autonomias$Comunidad[i]))
p4


r1=r1_raw[aceptados$V1,]
r1$dis=aceptados$dis

r1ord=gather(r1,key="dia",value="cantos",-V1,-dis)
r1ord$dia=as.Date(r1ord$dia)

m=max(100*r1ord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p5=ggplot(r1ord) +
   geom_line(aes(dia, 100*cantos/poboacioni,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("% of R1 in ", autonomias$Comunidad[i]))
p5

r2=r2_raw[aceptados$V1,]
r2$dis=aceptados$dis

r2ord=gather(r2,key="dia",value="cantos",-V1,-dis)
r2ord$dia=as.Date(r2ord$dia)

m=max(100*r2ord$cantos/poboacioni)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p6=ggplot(r2ord) +
   geom_line(aes(dia, 100*cantos/poboacioni,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") + scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("% of R2 in ", autonomias$Comunidad[i]))
p6

totord=gather(i1+i2+i3+r1+r2,key="dia",value="cantos",-V1,-dis)
totord$dia=as.Date(totord$dia)
totord$dis=i1ord$dis

m=max(totord$cantos)
div=m/8

step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p7=ggplot(totord) +
    geom_line(aes(dia, cantos,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +  
  scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+
  theme_bw() +
 
theme(plot.title = element_text(size = 20, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("All affected individuals (I1 + I2 + I3 + R1 + R2) in ", autonomias$Comunidad[i]))
p7


rtotord=gather(r1+r2,key="dia",value="cantos",-V1,-dis)
rtotord$dia=as.Date(rtotord$dia)
rtotord$dis=i1ord$dis

 m=max(rtotord$cantos)
div=m/8
step=(ceiling(div/10))*10


step=(ceiling(div/10^floor(log10(div))))*(10^floor(log10(div)))
p8=ggplot(rtotord) +
    geom_line(aes(dia, cantos,group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date(breaks = "1 week",date_labels ="%b %d") +
  scale_y_continuous(limits = c(0,m), 
                       breaks = seq(0,m, by = step))+

  theme_bw() +
 
 theme(plot.title = element_text(size = 30, face = "bold"),text = element_text(size=22)) +
  labs(x = "Date", y = "") +
  ggtitle(paste("All recovered individuals (R1 + R2) in ", autonomias$Comunidad[i]))
p8

```

```{r echo=FALSE, fig.height=8, fig.width=16}
p1
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p2
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p3
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p4
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p5
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p6
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p7
```
```{r echo=FALSE, fig.height=8, fig.width=16}
p8
```





```{r message=FALSE, warning=FALSE, include=FALSE}
png("Extremadura/Image_M.png",width=1600,height=800)
p1
dev.off()

jpeg("Extremadura/Image_M.jpg",width=960,height=540,quality = 50)
p1
dev.off()


png("Extremadura/Image_I1.png",width=1600,height=800)
p2
dev.off()

jpeg("Extremadura/Image_I1.jpg",width=960,height=540,quality = 50)
p2
dev.off()

png("Extremadura/Image_I2.png",width=1600,height=800)
p3
dev.off()

jpeg("Extremadura/Image_I2.jpg",width=960,height=540,quality = 50)
p3
dev.off()


png("Extremadura/Image_I3.png",width=1600,height=800)
p4
dev.off()

jpeg("Extremadura/Image_I3.jpg",width=960,height=540,quality = 50)
p4
dev.off()


png("Extremadura/Image_R1.png",width=1600,height=800)
p5
dev.off()

jpeg("Extremadura/Image_R1.jpg",width=960,height=540,quality = 50)
p5
dev.off()


png("Extremadura/Image_R2.png",width=1600,height=800)
p6
dev.off()

jpeg("Extremadura/Image_R2.jpg",width=960,height=540,quality = 50)
p6
dev.off()


png("Extremadura/Image_T.png",width=1600,height=800)
p7
dev.off()

jpeg("Extremadura/Image_T.jpg",width=960,height=540,quality = 50)
p7
dev.off()


png("Extremadura/Image_TR.png",width=1600,height=800)
p8
dev.off()

jpeg("Extremadura/Image_TR.jpg",width=960,height=540,quality = 50)
p8
dev.off()

```

