---
title: "Resultados"
author: "Carlos Meijide Garcia"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyr")
library("ggplot2")

# library("fda.usc")
# trayectorias= mortos_raw[,-1]
# datosfda= fdata(trayectorias)
# plot(datosfda)

#setwd("~/Modelo_Covid_descargado/Results/Navarra/")

##############################
##### CAMBIAR DENDE AQUÍ #####
##############################

i=13 #indice da autonomia

i1_raw= read.table("../src/Results/Madrid/SimulaMadrid_I1.txt")
i2_raw= read.table("../src/Results/Madrid/SimulaMadrid_I2.txt")
i3_raw= read.table("../src/Results/Madrid/SimulaMadrid_I3.txt")
r1_raw= read.table("../src/Results/Madrid/SimulaMadrid_R1.txt")
r2_raw= read.table("../src/Results/Madrid/SimulaMadrid_R2.txt")
mortos_raw=read.table("../src/Results/Madrid/SimulaMadrid_XM.txt")
erro=read.table("../src/Results/Madrid/SimulaMadrid_Error.txt")

autonomias=read.csv("../Data/Autonomias.csv",header=TRUE,sep='\t')

reais=read.csv("../Data/ccaa_covid19_fallecidos.csv",header=TRUE,sep=',')
####################
##### ATA AQUI #####
####################

reaisi=as.numeric(reais[(reais$cod_ine)==i,])

nceros=0
j=0
while(reaisi[j+3]==0) {
  nceros=nceros+1
  j=j+1
  }



d=ncol(mortos_raw)
r= 18-nceros#numero de dias con antelacion cos que empeza o simulador

datas=seq( as.Date("2020-03-03")-r, by=1, len=d-1)
names(i1_raw)[-1]=format(datas,"%Y-%m-%d")
names(i2_raw)[-1]=format(datas,"%Y-%m-%d")
names(i3_raw)[-1]=format(datas,"%Y-%m-%d")
names(r1_raw)[-1]=format(datas,"%Y-%m-%d")
names(r2_raw)[-1]=format(datas,"%Y-%m-%d")
names(mortos_raw)[-1]=format(datas,"%Y-%m-%d")



#marxe=as.double(erro[2])
morultimodia=as.double(erro[2])
distancias=(abs(mortos_raw[,ncol(mortos_raw)]-morultimodia))
mortos_raw$dis=distancias
ordenados=mortos_raw[order(mortos_raw$dis),]

aceptados=ordenados[ordenados$dis<0.5*morultimodia,]
mortos=aceptados




mord=gather(mortos,key="dia",value="cantos",-V1,-dis)

mord$dia=as.Date(mord$dia)

ggplot(mord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of dead in ", autonomias$Comunidad[i]))

 
i1=i1_raw[aceptados$V1,]
i1$dis=aceptados$dis

i1ord=gather(i1,key="dia",value="cantos",-V1,-dis)
i1ord$dia=as.Date(i1ord$dia)

ggplot(i1ord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of I1 in ", autonomias$Comunidad[i]))

i2=i2_raw[aceptados$V1,]
i2$dis=aceptados$dis

i2ord=gather(i2,key="dia",value="cantos",-V1,-dis)
i2ord$dia=as.Date(i1ord$dia)

ggplot(i2ord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of I2 in ", autonomias$Comunidad[i]))

i3=i3_raw[aceptados$V1,]
i3$dis=aceptados$dis

i3ord=gather(i3,key="dia",value="cantos",-V1,-dis)
i3ord$dia=as.Date(i1ord$dia)

ggplot(i3ord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of I3 in ", autonomias$Comunidad[i]))

r1=r1_raw[aceptados$V1,]
r1$dis=aceptados$dis

r1ord=gather(r1,key="dia",value="cantos",-V1,-dis)
r1ord$dia=as.Date(r1ord$dia)

ggplot(r1ord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of R1 in ", autonomias$Comunidad[i]))

r2=r2_raw[aceptados$V1,]
r2$dis=aceptados$dis

r2ord=gather(r2,key="dia",value="cantos",-V1,-dis)
r2ord$dia=as.Date(r2ord$dia)

ggplot(r2ord) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^100)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of R2 in ", autonomias$Comunidad[i]))
```
```{r}
totalcovid=gather(r1+r2+i1+i1+i3,key="dia",value="cantos",-V1,-dis)
totalcovid$dia=as.Date(totalcovid$dia)

ggplot(totalcovid) +
  geom_line(aes(dia, 100*cantos/autonomias$Población[i],group= V1,alpha=1/((1+dis)^2)),colour='#00C08D',show.legend=FALSE) +
  scale_x_date() +
  theme_bw() +
  labs(x = "Date", y = "", 
       subtitle = paste("% of total people affected by COVID-19 in ", autonomias$Comunidad[i]))
```


